import { COOKIE_NAME } from "@shared/const";
import { z } from "zod";
import {
  addCalendarEvent,
  createCardSet,
  createClassroom,
  createLearnerEvent,
  createPersonalBook,
  deletePersonalEntry,
  deleteLearnerEvent,
  deletePersonalBook,
  deleteCardSet,
  deleteStandardEntry,
  deleteRecommendedTest,
  deleteCalendarEvent,
  replaceStandardEntries,
  deleteStandardImportBatch,
  createStandardBook,
  completeDailySelect,
  claimNormalMission,
  evolveMonster,
  getDayDetail,
  getAdminOverview,
  getAdminCalendarDisplaySetting,
  listAdminAccounts,
  listClassrooms,
  getAdminAccountDetail,
  getDashboard,
  getDailySelectStatus,
  getDailyStudyJournalStatus,
  listDueReviewEntries,
  getMissionStatus,
  getNormalMissionStatus,
  getStudyJournalHistoryEntry,
  claimMission,
  claimAllMissions,
  recordMissionEvent,
  getWordEntries,
  gradeKanjiHandwriting,
  listAccessibleWordBooks,
  listStudyJournalHistory,
  listCardSets,
  loginLearner,
  publishAnnouncement,
  deleteAnnouncement,
  publishRecommendedTest,
  recordReview,
  recordTimerSession,
  resetAdminRevivalTickets,
  resetAdminAccountPin,
  replacePersonalEntries,
  saveStandardEntry,
  startDailySelect,
  savePersonalEntry,
  saveMonsterStage,
  saveEggDefinition,
  saveNormalMission,
  saveCreatureStageImage,
  saveAdminCalendarDisplaySetting,
  hatchEgg,
  useRevivalTicket,
  updateLearnerDisplayName,
  verifyAdminPassword,
} from "./db";
import { generateStudyJournal, generateTodayStudyJournal, STUDY_JOURNAL_LEVELS } from "./studyJournal";
import { gradeStudyJournalQuiz } from "./studyJournalQuiz";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, router } from "./_core/trpc";

const pin = z.string().regex(/^\d{4}$/, "4桁のPINコードを入力してください");
const category = z.enum(["english", "kanji"]);
const entry = z.object({ front: z.string().min(1).max(500), back: z.string().min(1).max(500), writingAnswer: z.string().max(500).optional().nullable() });
export const importEntriesInput = z.object({ pin, bookId: z.number().int().positive(), entries: z.array(entry).max(3000) });

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => {
      ctx.res.clearCookie(COOKIE_NAME, { ...getSessionCookieOptions(ctx.req), maxAge: -1 });
      return { success: true } as const;
    }),
  }),
  learning: router({
    dailySelectStatus: publicProcedure.input(z.object({ pin })).query(({ input }) => getDailySelectStatus(input.pin)),
    missionStatus: publicProcedure.input(z.object({ pin })).query(({ input }) => getMissionStatus(input.pin)),
    claimMission: publicProcedure.input(z.object({ pin, missionId: z.string().min(1).max(80) })).mutation(({ input }) => claimMission(input.pin, input.missionId)),
    claimAllMissions: publicProcedure.input(z.object({ pin })).mutation(({ input }) => claimAllMissions(input.pin)),
    normalMissionStatus: publicProcedure.input(z.object({ pin })).query(({ input }) => getNormalMissionStatus(input.pin)),
    claimNormalMission: publicProcedure.input(z.object({ pin, normalMissionId: z.number().int().positive() })).mutation(({ input }) => claimNormalMission(input.pin, input.normalMissionId)),
    hatchEgg: publicProcedure.input(z.object({ pin, eggId: z.number().int().positive() })).mutation(({ input }) => hatchEgg(input.pin, input.eggId)),
    recordMissionEvent: publicProcedure.input(z.object({ pin, eventType: z.enum(["test", "practice", "answer"]), category })).mutation(({ input }) => recordMissionEvent(input.pin, input.eventType, input.category)),
    startDailySelect: publicProcedure.input(z.object({ pin, category })).mutation(({ input }) => startDailySelect(input.pin, input.category)),
    completeDailySelect: publicProcedure.input(z.object({ pin, category })).mutation(({ input }) => completeDailySelect(input.pin, input.category)),
    evolveMonster: publicProcedure.input(z.object({ pin })).mutation(({ input }) => evolveMonster(input.pin)),
    generateStudyJournal: publicProcedure.input(z.object({ pin, category, level: z.enum(STUDY_JOURNAL_LEVELS) })).mutation(({ input }) => generateStudyJournal(input.pin, input.category, input.level)),
    dailyStudyJournalStatus: publicProcedure.input(z.object({ pin })).query(({ input }) => getDailyStudyJournalStatus(input.pin)),
    generateTodayStudyJournal: publicProcedure.input(z.object({ pin, category, level: z.enum(STUDY_JOURNAL_LEVELS) })).mutation(({ input }) => generateTodayStudyJournal(input.pin, input.category, input.level)),
    studyJournalHistory: publicProcedure.input(z.object({ pin })).query(({ input }) => listStudyJournalHistory(input.pin)),
    studyJournalHistoryEntry: publicProcedure.input(z.object({ pin, entryId: z.number().int().positive() })).query(({ input }) => getStudyJournalHistoryEntry(input.pin, input.entryId)),
    gradeStudyJournalQuiz: publicProcedure.input(z.object({ pin, entryId: z.number().int().positive(), answers: z.array(z.object({ questionId: z.string().min(1).max(80), answer: z.string().max(2000) })).max(6) })).mutation(({ input }) => gradeStudyJournalQuiz(input.pin, input.entryId, input.answers)),
    login: publicProcedure.input(z.object({ pin, classroomCode: z.string().trim().max(40).optional() })).mutation(({ input }) => loginLearner(input.pin, input.classroomCode)),
    dashboard: publicProcedure.input(z.object({ pin, category })).query(({ input }) => getDashboard(input.pin, input.category)),
    updateDisplayName: publicProcedure.input(z.object({ pin, displayName: z.string().trim().min(1, "名前を入力してください").max(40, "名前は40文字以内で入力してください") })).mutation(({ input }) => updateLearnerDisplayName(input.pin, input.displayName)),
    dueReviewEntries: publicProcedure.input(z.object({ pin, category })).query(({ input }) => listDueReviewEntries(input.pin, input.category)),
    books: publicProcedure.input(z.object({ pin, category })).query(({ input }) => listAccessibleWordBooks(input.pin, input.category)),
    entries: publicProcedure.input(z.object({ pin, bookId: z.number().int().positive() })).query(({ input }) => getWordEntries(input.pin, input.bookId)),
    cardSets: publicProcedure.input(z.object({ pin, category })).query(({ input }) => listCardSets(input.pin, input.category)),
    createBook: publicProcedure.input(z.object({ pin, category, name: z.string().trim().min(1).max(160) })).mutation(({ input }) => createPersonalBook(input.pin, input.category, input.name)),
    importEntries: publicProcedure.input(importEntriesInput).mutation(({ input }) => replacePersonalEntries(input.pin, input.bookId, input.entries)),
    savePersonalEntry: publicProcedure.input(z.object({ pin, id: z.number().int().positive().optional(), bookId: z.number().int().positive(), front: z.string().trim().min(1).max(500), back: z.string().trim().min(1).max(500), writingAnswer: z.string().max(500).optional().nullable() })).mutation(({ input }) => savePersonalEntry(input.pin, input)),
    deletePersonalEntry: publicProcedure.input(z.object({ pin, bookId: z.number().int().positive(), entryId: z.number().int().positive() })).mutation(({ input }) => deletePersonalEntry(input.pin, input.bookId, input.entryId)),
    createCardSet: publicProcedure.input(z.object({ pin, bookId: z.number().int().positive(), category, name: z.string().trim().min(1).max(120), startNo: z.number().int().positive(), endNo: z.number().int().positive() })).mutation(({ input }) => createCardSet(input.pin, input)),
    recordReview: publicProcedure.input(z.object({ pin, entryId: z.number().int().positive(), correct: z.boolean(), seconds: z.number().int().min(1).max(3600).optional() })).mutation(({ input }) => recordReview(input.pin, input.entryId, input.correct, input.seconds)),
    recordTimer: publicProcedure.input(z.object({ pin, seconds: z.number().int().min(1).max(7200) })).mutation(({ input }) => recordTimerSession(input.pin, input.seconds)),
    useRevivalTicket: publicProcedure.input(z.object({ pin, eventDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional() })).mutation(({ input }) => useRevivalTicket(input.pin, input.eventDate)),
    createPersonalEvent: publicProcedure.input(z.object({ pin, eventDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), title: z.string().trim().min(1).max(160) })).mutation(({ input }) => createLearnerEvent(input.pin, input)),
    deletePersonalEvent: publicProcedure.input(z.object({ pin, eventId: z.number().int().positive() })).mutation(({ input }) => deleteLearnerEvent(input.pin, input.eventId)),
    dayDetail: publicProcedure.input(z.object({ pin, category, date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/) })).query(({ input }) => getDayDetail(input.pin, input.category, input.date)),
    deletePersonalBook: publicProcedure.input(z.object({ pin, bookId: z.number().int().positive() })).mutation(({ input }) => deletePersonalBook(input.pin, input.bookId)),
    deleteCardSet: publicProcedure.input(z.object({ pin, cardSetId: z.number().int().positive() })).mutation(({ input }) => deleteCardSet(input.pin, input.cardSetId)),
    gradeKanjiHandwriting: publicProcedure.input(z.object({ pin, expectedKanji: z.string().trim().min(1).max(20), imageDataUrl: z.string().min(100).max(1_200_000), strictness: z.enum(["standard", "strict"]).default("standard") })).mutation(({ input }) => gradeKanjiHandwriting(input.imageDataUrl, input.expectedKanji, input.strictness)),
  }),
  admin: router({
    verify: publicProcedure.input(z.object({ password: z.string() })).mutation(({ input }) => verifyAdminPassword(input.password)),
    classrooms: publicProcedure.input(z.object({ password: z.string() })).query(({ input }) => listClassrooms(input.password)),
    createClassroom: publicProcedure.input(z.object({ password: z.string(), name: z.string().trim().min(1).max(120), teacherPassword: z.string().min(6).max(80) })).mutation(({ input }) => createClassroom(input.password, input)),
    overview: publicProcedure.input(z.object({ password: z.string() })).query(({ input }) => getAdminOverview(input.password)),
    calendarDisplaySetting: publicProcedure.input(z.object({ password: z.string() })).query(({ input }) => getAdminCalendarDisplaySetting(input.password)),
    saveCalendarDisplaySetting: publicProcedure.input(z.object({ password: z.string(), showCalendarExtras: z.boolean() })).mutation(({ input }) => saveAdminCalendarDisplaySetting(input.password, input.showCalendarExtras)),
    accounts: publicProcedure.input(z.object({ password: z.string() })).query(({ input }) => listAdminAccounts(input.password)),
    accountDetail: publicProcedure.input(z.object({ password: z.string(), learnerId: z.number().int().positive() })).query(({ input }) => getAdminAccountDetail(input.password, input.learnerId)),
    resetRevivalTickets: publicProcedure.input(z.object({ password: z.string(), learnerId: z.number().int().positive() })).mutation(({ input }) => resetAdminRevivalTickets(input.password, input.learnerId)),
    resetAccountPin: publicProcedure.input(z.object({ password: z.string(), learnerId: z.number().int().positive(), newPin: z.string().regex(/^\d{4}$/) })).mutation(({ input }) => resetAdminAccountPin(input.password, input.learnerId, input.newPin)),
    saveStandardEntry: publicProcedure.input(z.object({ password: z.string(), id: z.number().int().positive().optional(), bookId: z.number().int().positive(), entryNo: z.number().int().positive(), front: z.string().min(1).max(500), back: z.string().min(1).max(500), writingAnswer: z.string().max(500).optional().nullable() })).mutation(({ input }) => saveStandardEntry(input.password, input)),
    createStandardBook: publicProcedure.input(z.object({ password: z.string(), category, name: z.string().trim().min(1).max(160) })).mutation(({ input }) => createStandardBook(input.password, input.category, input.name)),
    deleteStandardEntry: publicProcedure.input(z.object({ password: z.string(), entryId: z.number().int().positive() })).mutation(({ input }) => deleteStandardEntry(input.password, input.entryId)),
    importStandardEntries: publicProcedure.input(z.object({ password: z.string(), bookId: z.number().int().positive(), entries: z.array(entry).max(3000) })).mutation(({ input }) => replaceStandardEntries(input.password, input.bookId, input.entries)),
    deleteStandardImportBatch: publicProcedure.input(z.object({ password: z.string(), bookId: z.number().int().positive(), batchId: z.string().length(32) })).mutation(({ input }) => deleteStandardImportBatch(input.password, input.bookId, input.batchId)),
    deleteRecommendedTest: publicProcedure.input(z.object({ password: z.string(), testId: z.number().int().positive() })).mutation(({ input }) => deleteRecommendedTest(input.password, input.testId)),
    deleteCalendarEvent: publicProcedure.input(z.object({ password: z.string(), eventId: z.number().int().positive() })).mutation(({ input }) => deleteCalendarEvent(input.password, input.eventId)),
    publishAnnouncement: publicProcedure.input(z.object({ password: z.string(), title: z.string().trim().min(1).max(160), body: z.string().trim().min(1).max(2000) })).mutation(({ input }) => publishAnnouncement(input.password, input.title, input.body)),
    deleteAnnouncement: publicProcedure.input(z.object({ password: z.string(), announcementId: z.number().int().positive() })).mutation(({ input }) => deleteAnnouncement(input.password, input.announcementId)),
    publishRecommendedTest: publicProcedure.input(z.object({ password: z.string(), title: z.string().trim().min(1).max(160), category, bookId: z.number().int().positive(), startNo: z.number().int().positive(), endNo: z.number().int().positive(), questionCount: z.number().int().min(1).max(100), startDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), endDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/) })).mutation(({ input }) => publishRecommendedTest(input.password, input)),
    addCalendarEvent: publicProcedure.input(z.object({ password: z.string(), eventDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), title: z.string().trim().min(1).max(160), category: z.enum(["english", "kanji", "both"]) })).mutation(({ input }) => addCalendarEvent(input.password, input)),
    saveMonsterStage: publicProcedure.input(z.object({ password: z.string(), stage: z.number().int().min(1).max(13), imageDataUrl: z.string().min(100).max(7_000_000) })).mutation(({ input }) => saveMonsterStage(input.password, input.stage, input.imageDataUrl)),
    saveEggDefinition: publicProcedure.input(z.object({ password: z.string(), id: z.number().int().positive().optional(), name: z.string().trim().min(1).max(120), description: z.string().trim().max(500), isActive: z.boolean() })).mutation(({ input }) => saveEggDefinition(input.password, input)),
    saveNormalMission: publicProcedure.input(z.object({ password: z.string(), id: z.number().int().positive().optional(), title: z.string().trim().min(1).max(160), targetStudySeconds: z.number().int().min(3600).max(100_000_000), rewardEggDefinitionId: z.number().int().positive(), sortOrder: z.number().int().min(0).max(1000), isActive: z.boolean() })).mutation(({ input }) => saveNormalMission(input.password, input)),
    saveCreatureStageImage: publicProcedure.input(z.object({ password: z.string(), eggDefinitionId: z.number().int().positive(), stage: z.number().int().min(1).max(13), imageDataUrl: z.string().min(100).max(7_000_000) })).mutation(({ input }) => saveCreatureStageImage(input.password, input.eggDefinitionId, input.stage, input.imageDataUrl)),
  }),
});

export type AppRouter = typeof appRouter;
